// External packages
import type { Metadata } from 'next';
import localFont from 'next/font/local';

// Styles
import '../styles/globals.css';

const MonaSansFont = localFont({
	src: '../public/fonts/Mona-Sans.ttf',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body
				className={`${MonaSansFont.className} bg-background text-background-foreground`}
			>
				{children}
			</body>
		</html>
	);
}
