// External packages
import type { Metadata } from 'next';
import localFont from 'next/font/local';

// Components
import { Toaster } from '@/components/ui/toast';
import { ThemeProvider } from 'next-themes';

// Styles
import '../styles/globals.css';

const MonaSansFont = localFont({
	src: '../public/fonts/Mona-Sans.ttf',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${MonaSansFont.className} bg-background text-background-foreground`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
				<Toaster />
			</body>
		</html>
	);
}
