// External packages

import type { Metadata } from "next";
import localFont from "next/font/local";

// Styles
import "../styles/globals.css";

const MonaSansFont = localFont({
  src: "../styles/fonts/Mona-Sans.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${MonaSansFont.className}`}>{children}</body>
    </html>
  );
}
